import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Box } from "@chakra-ui/react";
import { ContactUs } from "../src/components/contactUs";
import {Nav} from "../src/components/Nav";
import { Benefits } from "../src/components/Benefits";
import { Competition } from "../src/components/Competition";
import { Footer } from "../src/components/Footer";
import {Faq} from "../src/components/Faq";
import { Register } from "../src/components/Register";
import { Stages } from "../src/components/Stages";
import { Topbar } from "../src/components/Topbar";

const Home: NextPage = () => {
  return (
    <Box>
      <Head>
        <title>
          uLesson | No. 1 Learning App for Primary, Junior & Secondary School
          Students
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Topbar/>
      <Benefits />
      <Competition />
      <Stages />
      <Register />
      <Faq />
      <ContactUs />
      <Footer />
    </Box>
  );
};

export default Home;
